### ISSUE TITLE
Tab Candidates: Create notifications

### ISSUE THREAD

**Issue by margaritamikulionok** [43gfm28/Training-team-6#39]
Task Description:
1. Create notifications
2. Using JSON file fill in the notifications
3. Using JSON file fill in the schedule of interview
4. Create the button 'view all'
5. Clicking on 'view all' page expands the list of notifications
6. Add close button on each notification
![image](https://user-images.githubusercontent.com/33221440/37356014-162912f2-26f6-11e8-95ca-24ff8c4c7e1d.png)

**Comment by oupoboros** [comment]
По какому принципу идёт добавление в new candidates, есть какие-нибудь временные ограничения?
